name: CI
on: 
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Sets tsx for test exec
        run: npm i --no-package-lock --no-save tsx

      - name: Tests for valid Database connection
        run: npm test 