name: CI
on: 
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Debug package.json path
        shell: pwsh
        run: ls .

      - name: Tests for valid Database connection
        run: npm test 